---
apiVersion: v1
kind: Service
metadata:
  name: {{service.name}}
spec:
  selector:
    app: {{service.name}}
  ports:
    - port: 80
      targetPort: http-api
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{service.name}}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{service.name}}
    spec:
      containers:
      - name: {{service.name}}
        image: {{build.images["Dockerfile"]}}
        imagePullPolicy: Always
        ports:
        - name: http-api
          containerPort: 5000
