---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: qotm
  namespace: tutorial
spec:
  replicas: 3
  strategy:
    type: RollingUpdate  
  template:
    metadata:
      labels:
        app: qotm
    spec:
      containers:
      - name: qotm
        image: datawire/qotm:1.0
        ports:
        - name: http-api 
          containerPort: 5000
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
