---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotm
  namespace: test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: qotm
  template:
    metadata:
      labels:
        app: qotm
      annotations:
        linkerd.io/inject: "enabled"
        config.linkerd.io/skip-outbound-ports: "8081,8022,6000-7999"
    spec:
      containers:
      - name: qotm
        image: docker.io/datawire/qotm:1.7
        ports:
        - name: http-api
          containerPort: 5000
        env:
        - name: CONSUL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 3
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
